Length: 12
Height: 18
Column Length: 15
Last Color: 3
Slots:
- Start: 0
  End: 1
  Name: Static
  Format: "\e[31m"
- Start: 2
  End: 2
  Name: Slot 1
  Format: "\e[32m"
- Start: 4
  End: 4
  Name: Slot 2
  Format: "\e[33m"
Points:
- x: 2
  y: 1
- x: 4
  y: 1
Format:
  X0Y0: "\e[31m"
  X1Y0: "\e[31m"
  X2Y0: "\e[32m"
  X4Y0: "\e[33m"
  X0Y1: "\e[31m"
  X1Y1: "\e[31m"
  X2Y1: "\e[32m\e[1m\e[3m"
  X4Y1: "\e[33m\e[1m\e[3m"
  X0Y2: "\e[31m"
  X1Y2: "\e[31m"
  X2Y2: "\e[32m"
  X4Y2: "\e[33m"
  X0Y3: "\e[31m"
  X1Y3: "\e[31m"
  X2Y3: "\e[32m"
  X4Y3: "\e[33m"
  X0Y4: "\e[31m"
  X1Y4: "\e[31m"
  X2Y4: "\e[32m"
  X4Y4: "\e[33m"
  X0Y5: "\e[31m"
  X1Y5: "\e[31m"
  X2Y5: "\e[32m"
  X4Y5: "\e[33m"
  X0Y6: "\e[31m"
  X1Y6: "\e[31m"
  X2Y6: "\e[32m"
  X4Y6: "\e[33m"
  X0Y7: "\e[31m"
  X1Y7: "\e[31m"
  X2Y7: "\e[32m"
  X4Y7: "\e[33m"
  X0Y8: "\e[31m"
  X1Y8: "\e[31m"
  X2Y8: "\e[32m"
  X4Y8: "\e[33m"
  X0Y9: "\e[31m"
  X1Y9: "\e[31m"
  X2Y9: "\e[32m"
  X4Y9: "\e[33m"
  X0Y10: "\e[31m"
  X1Y10: "\e[31m"
  X2Y10: "\e[32m"
  X4Y10: "\e[33m"
  X0Y11: "\e[31m"
  X1Y11: "\e[31m"
  X2Y11: "\e[32m"
  X4Y11: "\e[33m"
  X0Y12: "\e[31m"
  X1Y12: "\e[31m"
  X2Y12: "\e[32m"
  X4Y12: "\e[33m"
  X0Y13: "\e[31m"
  X1Y13: "\e[31m"
  X2Y13: "\e[32m"
  X4Y13: "\e[33m"
  X0Y14: "\e[31m"
  X1Y14: "\e[31m"
  X2Y14: "\e[32m"
  X4Y14: "\e[33m"
  X0Y15: "\e[31m"
  X1Y15: "\e[31m"
  X2Y15: "\e[32m"
  X4Y15: "\e[33m"
  X0Y16: "\e[31m"
  X1Y16: "\e[31m"
  X2Y16: "\e[32m"
  X4Y16: "\e[33m"
  X0Y17: "\e[31m"
  X1Y17: "\e[31m"
  X2Y17: "\e[32m"
  X4Y17: "\e[33m"
