Length: 12
Height: 18
Column Length: 15
Last Color: 3
Slots:
- Start: 0
  End: 1
  Name: Static
  Format: "\e[31m"
- Start: 2
  End: 2
  Name: Slot 1
  Format: "\e[32m"
- Start: 4
  End: 4
  Name: Slot 2
  Format: "\e[33m"
Points:
- x: 2
  y: 1
- x: 4
  y: 1
Format:
  X0Y0: "\e[31m"
  X1Y0: "\e[31m"
  X2Y0: "\e[32m"
  X3Y0: "\e[0m"
  X4Y0: "\e[33m"
  X5Y0: "\e[0m"
  X6Y0: "\e[0m"
  X7Y0: "\e[0m"
  X8Y0: "\e[0m"
  X9Y0: "\e[0m"
  X10Y0: "\e[0m"
  X11Y0: "\e[0m"
  X0Y1: "\e[31m"
  X1Y1: "\e[31m"
  X2Y1: "\e[32m\e[1m\e[3m"
  X3Y1: "\e[0m"
  X4Y1: "\e[33m\e[1m\e[3m"
  X5Y1: "\e[0m"
  X6Y1: "\e[0m"
  X7Y1: "\e[0m"
  X8Y1: "\e[0m"
  X9Y1: "\e[0m"
  X10Y1: "\e[0m"
  X11Y1: "\e[0m"
  X0Y2: "\e[31m"
  X1Y2: "\e[31m"
  X2Y2: "\e[32m"
  X3Y2: "\e[0m"
  X4Y2: "\e[33m"
  X5Y2: "\e[0m"
  X6Y2: "\e[0m"
  X7Y2: "\e[0m"
  X8Y2: "\e[0m"
  X9Y2: "\e[0m"
  X10Y2: "\e[0m"
  X11Y2: "\e[0m"
  X0Y3: "\e[31m"
  X1Y3: "\e[31m"
  X2Y3: "\e[32m"
  X3Y3: "\e[0m"
  X4Y3: "\e[33m"
  X5Y3: "\e[0m"
  X6Y3: "\e[0m"
  X7Y3: "\e[0m"
  X8Y3: "\e[0m"
  X9Y3: "\e[0m"
  X10Y3: "\e[0m"
  X11Y3: "\e[0m"
  X0Y4: "\e[31m"
  X1Y4: "\e[31m"
  X2Y4: "\e[32m"
  X3Y4: "\e[0m"
  X4Y4: "\e[33m"
  X5Y4: "\e[0m"
  X6Y4: "\e[0m"
  X7Y4: "\e[0m"
  X8Y4: "\e[0m"
  X9Y4: "\e[0m"
  X10Y4: "\e[0m"
  X11Y4: "\e[0m"
  X0Y5: "\e[31m"
  X1Y5: "\e[31m"
  X2Y5: "\e[32m"
  X3Y5: "\e[0m"
  X4Y5: "\e[33m"
  X5Y5: "\e[0m"
  X6Y5: "\e[0m"
  X7Y5: "\e[0m"
  X8Y5: "\e[0m"
  X9Y5: "\e[0m"
  X10Y5: "\e[0m"
  X11Y5: "\e[0m"
  X0Y6: "\e[31m"
  X1Y6: "\e[31m"
  X2Y6: "\e[32m"
  X3Y6: "\e[0m"
  X4Y6: "\e[33m"
  X5Y6: "\e[0m"
  X6Y6: "\e[0m"
  X7Y6: "\e[0m"
  X8Y6: "\e[0m"
  X9Y6: "\e[0m"
  X10Y6: "\e[0m"
  X11Y6: "\e[0m"
  X0Y7: "\e[31m"
  X1Y7: "\e[31m"
  X2Y7: "\e[32m"
  X3Y7: "\e[0m"
  X4Y7: "\e[33m"
  X5Y7: "\e[0m"
  X6Y7: "\e[0m"
  X7Y7: "\e[0m"
  X8Y7: "\e[0m"
  X9Y7: "\e[0m"
  X10Y7: "\e[0m"
  X11Y7: "\e[0m"
  X0Y8: "\e[31m"
  X1Y8: "\e[31m"
  X2Y8: "\e[32m"
  X3Y8: "\e[0m"
  X4Y8: "\e[33m"
  X5Y8: "\e[0m"
  X6Y8: "\e[0m"
  X7Y8: "\e[0m"
  X8Y8: "\e[0m"
  X9Y8: "\e[0m"
  X10Y8: "\e[0m"
  X11Y8: "\e[0m"
  X0Y9: "\e[31m"
  X1Y9: "\e[31m"
  X2Y9: "\e[32m"
  X3Y9: "\e[0m"
  X4Y9: "\e[33m"
  X5Y9: "\e[0m"
  X6Y9: "\e[0m"
  X7Y9: "\e[0m"
  X8Y9: "\e[0m"
  X9Y9: "\e[0m"
  X10Y9: "\e[0m"
  X11Y9: "\e[0m"
  X0Y10: "\e[31m"
  X1Y10: "\e[31m"
  X2Y10: "\e[32m"
  X3Y10: "\e[0m"
  X4Y10: "\e[33m"
  X5Y10: "\e[0m"
  X6Y10: "\e[0m"
  X7Y10: "\e[0m"
  X8Y10: "\e[0m"
  X9Y10: "\e[0m"
  X10Y10: "\e[0m"
  X11Y10: "\e[0m"
  X0Y11: "\e[31m"
  X1Y11: "\e[31m"
  X2Y11: "\e[32m"
  X3Y11: "\e[0m"
  X4Y11: "\e[33m"
  X5Y11: "\e[0m"
  X6Y11: "\e[0m"
  X7Y11: "\e[0m"
  X8Y11: "\e[0m"
  X9Y11: "\e[0m"
  X10Y11: "\e[0m"
  X11Y11: "\e[0m"
  X0Y12: "\e[31m"
  X1Y12: "\e[31m"
  X2Y12: "\e[32m"
  X3Y12: "\e[0m"
  X4Y12: "\e[33m"
  X5Y12: "\e[0m"
  X6Y12: "\e[0m"
  X7Y12: "\e[0m"
  X8Y12: "\e[0m"
  X9Y12: "\e[0m"
  X10Y12: "\e[0m"
  X11Y12: "\e[0m"
  X0Y13: "\e[31m"
  X1Y13: "\e[31m"
  X2Y13: "\e[32m"
  X3Y13: "\e[0m"
  X4Y13: "\e[33m"
  X5Y13: "\e[0m"
  X6Y13: "\e[0m"
  X7Y13: "\e[0m"
  X8Y13: "\e[0m"
  X9Y13: "\e[0m"
  X10Y13: "\e[0m"
  X11Y13: "\e[0m"
  X0Y14: "\e[31m"
  X1Y14: "\e[31m"
  X2Y14: "\e[32m"
  X3Y14: "\e[0m"
  X4Y14: "\e[33m"
  X5Y14: "\e[0m"
  X6Y14: "\e[0m"
  X7Y14: "\e[0m"
  X8Y14: "\e[0m"
  X9Y14: "\e[0m"
  X10Y14: "\e[0m"
  X11Y14: "\e[0m"
  X0Y15: "\e[31m"
  X1Y15: "\e[31m"
  X2Y15: "\e[32m"
  X3Y15: "\e[0m"
  X4Y15: "\e[33m"
  X5Y15: "\e[0m"
  X6Y15: "\e[0m"
  X7Y15: "\e[0m"
  X8Y15: "\e[0m"
  X9Y15: "\e[0m"
  X10Y15: "\e[0m"
  X11Y15: "\e[0m"
  X0Y16: "\e[31m"
  X1Y16: "\e[31m"
  X2Y16: "\e[32m"
  X3Y16: "\e[0m"
  X4Y16: "\e[33m"
  X5Y16: "\e[0m"
  X6Y16: "\e[0m"
  X7Y16: "\e[0m"
  X8Y16: "\e[0m"
  X9Y16: "\e[0m"
  X10Y16: "\e[0m"
  X11Y16: "\e[0m"
  X0Y17: "\e[31m"
  X1Y17: "\e[31m"
  X2Y17: "\e[32m"
  X3Y17: "\e[0m"
  X4Y17: "\e[33m"
  X5Y17: "\e[0m"
  X6Y17: "\e[0m"
  X7Y17: "\e[0m"
  X8Y17: "\e[0m"
  X9Y17: "\e[0m"
  X10Y17: "\e[0m"
  X11Y17: "\e[0m"
